### PR TITLE
Fix transparent backgrounds

### PR DESCRIPTION
**Pull request by elixir-zatech**
Hey,

I fixed the ones I could, replacing the jpgs with pngs. The others are a bit more problematic because they're things like java logos which have white baked into them or they're animated or they're low quality so they break when removing.

### CODE REVIEW

**Comment by mchampanis** [comment]
`.jpg`s need to be deleted?

**Comment by elixir-zatech** [comment]
@mchampanis JPEG can't support transparency because it uses RGB color space. :)

**Comment by mchampanis** [comment]
i mean, it looks like the old jpgs are still there:

image

my poorly phrased question was, i think they need to be deleted from repo

**Comment by elixir-zatech** [comment]
Ah! no worries @mchampanis if you click on the right diff it will show you "the file has been deleted", it's gone. It just shows it like that for some reason...

**Comment by elixir-zatech** [comment]
Screenshot 2020-01-31 at 12 59 07

**Comment by mchampanis** [comment]
oh, got it. weird, i thought it used to say "deleted file" in either mode.

**Pull request merged**
