### PR TITLE
add :facepalm: emoji

### PR DESCRIPTION
**Pull request by Satraan**

### CODE REVIEW

**Comment by mchampanis** [comment]
i think it's one emoji per PR @Satraan - @n1c?

**Comment by Satraan** [comment]
Yep, removed the second one. My bad

**Comment by n1c** [comment]
There's already a :face_palm: in the Slack stdlib so this might work better with some prefix/suffix like :picard_facepalm:

**Comment by mchampanis** [comment]
image

would suggest `:picard-facepalming:` based on above

**Comment by Vulcanit3** [comment]
Most other formats we use are suffix heavy rather than prefix.
I'd suggest :facepalm_picard:
Similarly there used to be a lot of :dancing_<thing>: emojis (which I'm keen to MR back at some point)

We use that for channels too, so could be a bit nicer. All the same from a fuzzy search PoV though

**Comment by Satraan** [comment]
I blame @Vulcanit3 entirely for the git butchery here 😅

**Comment by Vulcanit3** [comment]
Can't even put ` in a commit message on mac without it freaking out :|
:donotwant:

**Pull request merged**
