### PR TITLE
Added :mrbean:

### PR DESCRIPTION
**Pull request by Vulcanit3**

### CODE REVIEW

**Comment by n1c** [comment]
What's like the "meaning" of this emoji?

I never really got it's usage other than the "that joke/reference/thing is kinda sexual"?

**Comment by mchampanis** [comment]
@n1c: what's the general policy here? i wasn't sure whether to approve this, `:dadjoke:`, `:pitchfork:`, etc.

they aren't harmful/ill-meaning, but also are quite generic. are we okay with having a ton of emojis as long as they fall into the "this is okay" heuristic (i.e. was the issue more that there were too many emojis/too many duplicates, or that there were harmful emojis in the collection)?

**Comment by n1c** [comment]
In summary there isn't a policy and we're kind of fumbling our way around!

**Comment by datashaman** [comment]
If someone says something saucy or unbelievable, it's a std response. Something like :orly: but with more innuendo.

**Comment by Vulcanit3** [comment]
I don't really have a lot of context on this one. I've never seen it as `thing is kinda sexual` though to be honest. More like a joke, :mindblown: etc


With regards to :pitchfork: and :dadjoke: those are pretty wholesome.
Pitchfork is used like 99% as a joke (think Shrek)
dadjoke is the `chortle`, much like this meme ==> https://static.independent.co.uk/s3fs-public/indy100/by0jWOHOTl/19112-1r13i1t.jpg

**Comment by mchampanis** [comment]
@n1c

**Pull request merged**
