### PR TITLE
add :pathetic:

### PR DESCRIPTION
**Pull request by zkrige**

### CODE REVIEW

**Comment by elixir-zatech** [comment]
👍

**Comment by mchampanis** [comment]
@zkrige what did you think about: https://github.com/zatech/emojis/pull/52#pullrequestreview-347201528 ?

**Comment by zkrige** [comment]
> @zkrige what did you think about: [#52 (review)](https://github.com/zatech/emojis/pull/52#pullrequestreview-347201528) ?

Thanks @mchampanis - I've made your suggested changes

**Comment by zoidbergwill** [comment]
I can't think of positive constructive uses for a `:pathetic:` emoji? Could we call it `:principal_skinner:` or something, instead?

**Comment by zkrige** [comment]
For humor. It’s quite fun. It sometimes livens up boring environments and makes life bearable. Not everything in life needs to be looked at so cynically

**Comment by elixir-zatech** [comment]
I second z' comment, :pathetic: is being actively used all over the place. Even Adrian is using it. However since I seconded this, it was almost undoubtedly be thrown into the trash fires of rejection.

**Comment by zkrige** [comment]
> I second z' comment, :pathetic: is being actively used all over the place. Even Adrian is using it. However since I seconded this, it was almost undoubtedly be thrown into the trash fires of rejection.

:pathetic:

**Comment by elixir-zatech** [comment]
I removed the above comment <3

**Comment by n1c** [comment]
🕯

**Pull request closed without merging**
